### ISSUE TITLE
TikTokBlockChangeChallenge

### ISSUE THREAD

**Issue by Zune24** [ImmerNochNoah/TikTokBlockChangeChallenge#1]
Hello, could you help me how to install TikTokBlockChangeChallenge? I can't get it to work or do I have to convert it to a .jar? it does not let me

**Comment by ImmerNochNoah** [comment]
Hello, you have to download the plugin from here https://github.com/ImmerNochNoah/TikTokBlockChangeChallenge/releases/tag/v0.0.1
Then you have to put the plugin in your plugins folder and restart the server. 
/start and the challenge starts. 
I hope this helps you :)
